# myfile=open("file.txt",'r+')
# myfile.write("MANIDEEP")
# myfile=open("file.txt",'r')
#myfile=open("file1.txt",'r')
# x=myfile.read()
# print(x)
# myfile.close()

# myfile=open('file.txt','r')
# x=myfile.read()
# print(str(x))
# myfile.close
myfile=open("file.txt",'a+')
a=input("enter aname")
myfile.write(a+"\n")
print(myfile.tell())
myfile.seek(0)
x=myfile.read()
print(x)
myfile.close()